Traceback (most recent call last):
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\nbclient\client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\nbclient\util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\nbclient\util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\nbclient\client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\nbclient\client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\bjtja\anaconda3\envs\test_update_py\lib\site-packages\nbclient\client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
reload(StatArrays)
# Generate stats
stats_13th_age = [StatArrays.thirtheenth_age() for i in range(num_iterations)]
stats_13th_age = PandasHelper.stats_arrays_to_pd(stats_13th_age, "13th Age")
stats_13th_age = pd.concat([stats[["4d6-drop-lowest", "Improved Caterpillar"]], stats_13th_age], axis=1)

point_buy_13th_age = stats_13th_age.replace(StatArrays.point_buy_dict).groupby("iter").sum()
totals_13th_age = stats_13th_age.groupby("iter").sum()

# Create stat distribution graph
fig_13th_age, axes = plt.subplots(ncols=2, figsize=(8, 4))

stat_counts = PandasHelper.create_counts(stats_13th_age, normalize=True)
[line_plot(axes[0], stat_counts, c) for c in stat_counts.columns]
num_samples = StatArrays.num_ability_scores*num_iterations
axes[0].set_ylabel(f"Distribution (out of {num_samples:,} samples)")
axes[0].set_xlabel("Ability score")
percent_formatter = matplotlib.ticker.PercentFormatter(xmax=1, decimals=1)
axes[0].yaxis.set_major_formatter(percent_formatter)
axes[0].legend()
axes[0].grid(True)

# Create point buy budget distribution
point_buy_counts = PandasHelper.create_counts(point_buy_13th_age, normalize=True)
[line_plot(axes[1], point_buy_counts, c) for c in point_buy_counts.columns]
axes[1].set_ylabel(f"Distribution (out of {num_iterations:,} samples)")
percent_formatter = matplotlib.ticker.PercentFormatter(xmax=1, decimals=1)
axes[1].yaxis.set_major_formatter(percent_formatter)
axes[1].set_xlabel("Point buy budget")
axes[1].legend()
axes[1].grid(True)

fig_13th_age.tight_layout()

glue("13th_age_fig", fig_13th_age, display=False)
glue("13th_age_stats", stats_13th_age.describe())
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mKeyError[0m                                  Traceback (most recent call last)
[1;32m~\AppData\Local\Temp/ipykernel_10660/1656028701.py[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [0mstats_13th_age[0m [1;33m=[0m [0mpd[0m[1;33m.[0m[0mconcat[0m[1;33m([0m[1;33m[[0m[0mstats[0m[1;33m[[0m[1;33m[[0m[1;34m"4d6-drop-lowest"[0m[1;33m,[0m [1;34m"Improved Caterpillar"[0m[1;33m][0m[1;33m][0m[1;33m,[0m [0mstats_13th_age[0m[1;33m][0m[1;33m,[0m [0maxis[0m[1;33m=[0m[1;36m1[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [1;33m[0m[0m
[1;32m----> 7[1;33m [0mpoint_buy_13th_age[0m [1;33m=[0m [0mstats_13th_age[0m[1;33m.[0m[0mreplace[0m[1;33m([0m[0mStatArrays[0m[1;33m.[0m[0mpoint_buy_dict[0m[1;33m)[0m[1;33m.[0m[0mgroupby[0m[1;33m([0m[1;34m"iter"[0m[1;33m)[0m[1;33m.[0m[0msum[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m [0mtotals_13th_age[0m [1;33m=[0m [0mstats_13th_age[0m[1;33m.[0m[0mgroupby[0m[1;33m([0m[1;34m"iter"[0m[1;33m)[0m[1;33m.[0m[0msum[0m[1;33m([0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0;32m      9[0m [1;33m[0m[0m

[1;32m~\anaconda3\envs\test_update_py\lib\site-packages\pandas\core\frame.py[0m in [0;36mgroupby[1;34m(self, by, axis, level, as_index, sort, group_keys, squeeze, observed, dropna)[0m
[0;32m   7624[0m         [1;31m# error: Argument "squeeze" to "DataFrameGroupBy" has incompatible type[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m   7625[0m         [1;31m# "Union[bool, NoDefault]"; expected "bool"[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[1;32m-> 7626[1;33m         return DataFrameGroupBy(
[0m[0;32m   7627[0m             [0mobj[0m[1;33m=[0m[0mself[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m   7628[0m             [0mkeys[0m[1;33m=[0m[0mby[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\test_update_py\lib\site-packages\pandas\core\groupby\groupby.py[0m in [0;36m__init__[1;34m(self, obj, keys, axis, level, grouper, exclusions, selection, as_index, sort, group_keys, squeeze, observed, mutated, dropna)[0m
[0;32m    886[0m             [1;32mfrom[0m [0mpandas[0m[1;33m.[0m[0mcore[0m[1;33m.[0m[0mgroupby[0m[1;33m.[0m[0mgrouper[0m [1;32mimport[0m [0mget_grouper[0m[1;33m[0m[1;33m[0m[0m
[0;32m    887[0m [1;33m[0m[0m
[1;32m--> 888[1;33m             grouper, exclusions, obj = get_grouper(
[0m[0;32m    889[0m                 [0mobj[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    890[0m                 [0mkeys[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m

[1;32m~\anaconda3\envs\test_update_py\lib\site-packages\pandas\core\groupby\grouper.py[0m in [0;36mget_grouper[1;34m(obj, key, axis, level, sort, observed, mutated, validate, dropna)[0m
[0;32m    858[0m                 [0min_axis[0m[1;33m,[0m [0mlevel[0m[1;33m,[0m [0mgpr[0m [1;33m=[0m [1;32mFalse[0m[1;33m,[0m [0mgpr[0m[1;33m,[0m [1;32mNone[0m[1;33m[0m[1;33m[0m[0m
[0;32m    859[0m             [1;32melse[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 860[1;33m                 [1;32mraise[0m [0mKeyError[0m[1;33m([0m[0mgpr[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    861[0m         [1;32melif[0m [0misinstance[0m[1;33m([0m[0mgpr[0m[1;33m,[0m [0mGrouper[0m[1;33m)[0m [1;32mand[0m [0mgpr[0m[1;33m.[0m[0mkey[0m [1;32mis[0m [1;32mnot[0m [1;32mNone[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    862[0m             [1;31m# Add key to exclusions[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m

[1;31mKeyError[0m: 'iter'
KeyError: 'iter'

